spring:
  datasource:
     # mariaDB
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/jjplatform?serverTimezone=UTC&characterEncoding=UTF-8
#    url: ENC(GBwofgLMHoSsQnpZibur3tWzVF5kKKVNwhx6a1pJKPwjwWg/XcqjPoN6rGmMXJMVOmN7n0mjC1dX34hWNt4ZYvhCzQnBk2luFYJ7IMmqxwo7sh76mt26WV3ogj9z8nhv
    # mssqlDB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=jjplatform
#    url: ENC(MmiTiP44lIRwwPxqvvoKIm1obI3cZp1miD4IpMy2QcclrnvULLoqmtMmrqgJgjttKl28jdqPSh/goaACkoobjQ==)
#    username: jjplatform
#    password: akfls5315!@
    username: ENC(KuzxL5DMolNzLk5xgLqjjfpPLf5HZPpf)
    password: ENC(vHZy9JLKQMM+JE7US6T1YlQykSg6B+K6)
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
      pool-name: JJPLATFormHikariCP
      maximum-pool-size: 2
      idle-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
