server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jjplatform
    username: jjplatform
    password: akfls0614!@
    
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # model 프로퍼티 camel case 설정
  configuration:
    map-underscore-to-camel-case: true
  # 패키지 명을 생략할 수 있도록 alias 설정
  type-aliases-package: com.jjplatform.admin.vo

# mapper 로그레벨 설정      
logging:
  level:
    root: WARN
    com.jjplatform.admin.dao: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO