SELECT D.COLORDER 					AS COLUMN_IDX 			/* Column Index */ 
	 , A.NAME 						AS TABLE_NAME 			/* Table Name */ 			
	 , C.VALUE 						AS TABLE_DESCRIPTION 	/* Table Description */ 
	 , CONCAT(', ', CAST(D.NAME AS VARCHAR), ' /* ', CAST(E.VALUE AS VARCHAR), ' */') 						AS COLNAME 				/* Column Name */ 
	 , E.VALUE AS COLDESC 				/* Column Description */ 
	 , CONCAT('<w2:column id="', CAST(D.NAME AS VARCHAR), '" name="',REPLACE(CAST(E.VALUE AS VARCHAR),' ' , ''), '" dataType="', CASE F.DATA_TYPE WHEN 'nvarchar' then 'text' WHEN 'numeric' THEN 'number' end, '"></w2:column>' ) AS dataList
	 , F.DATA_TYPE 					AS COLTYPE 				/* Column Type */ 
	 , (CASE WHEN F.DATA_TYPE != 'numeric' THEN (F.CHARACTER_OCTET_LENGTH/2) ELSE F.NUMERIC_PRECISION  END) 	AS COLLEN 				/* Column Length */ 
	 , D.SCALE 						AS SCALE 				/* Column Scale */ 
	 , F.IS_NULLABLE 				AS IS_NULLABLE 			/* Column Nullable */ 
	 , F.COLLATION_NAME 			AS COLLATION_NAME 		/* Column Collaction Name */ 
  FROM SYSOBJECTS A WITH (NOLOCK) 
	   INNER JOIN SYSUSERS B WITH (NOLOCK) ON A.UID = B.UID 
	   INNER JOIN SYSCOLUMNS D WITH (NOLOCK) ON D.ID = A.ID 
	   INNER JOIN INFORMATION_SCHEMA.COLUMNS F WITH (NOLOCK) ON A.NAME = F.TABLE_NAME 
															AND D.NAME = F.COLUMN_NAME 
	   LEFT OUTER JOIN SYS.EXTENDED_PROPERTIES C WITH (NOLOCK) ON C.MAJOR_ID = A.ID 
															  AND C.MINOR_ID = 0 
	   LEFT OUTER JOIN SYS.EXTENDED_PROPERTIES E WITH (NOLOCK) ON E.MAJOR_ID = D.ID 
															  AND E.MINOR_ID = D.COLID 
  															  AND E.NAME = 'MS_Description' 
 WHERE 1=1 
--   AND A.TYPE = 'U' 
   AND A.NAME = 'TBBA023'
--   AND C.VALUE LIKE '%변경%'
--   AND DATA_TYPE LIKE 'num%'
 ORDER BY -- D.COLORDER, 
          A.NAME;
         
         
select *
from TBBA001;

TBST014
tbif103;

select CONCAT(', ', '111', '		/* ', 'bbbb', ' */');

dbcc inputbuffer ( 83 );

EXEC SP_LOCK ;
EXEC SP_WHO2;
SELECT * FROM SYS.sysprocesses WHERE BLOCKED > 0;

kill 81;


SELECT
	           T0.USER_ID
	          , T0.USER_NM
			  , T0.GRP_ID
			  , CASE WHEN T6.USER_LVL = '0' OR T6.USER_LVL ='1' THEN '1' ELSE COALESCE(T6.USER_LVL,'41') END AS USER_LVL
			  , CASE WHEN T6.USER_LVL = '0' OR T6.USER_LVL ='1' THEN 'Y' ELSE 'N' END AS IS_ADMIN /* 시스템 관리자 */
			  , CASE WHEN T6.USER_LVL = '0' OR T6.USER_LVL ='21' THEN 'Y' ELSE 'N' END AS IS_CP_ADMIN /* 회사 관리자 */
			  , CASE WHEN T6.USER_LVL = '0' OR T6.USER_LVL ='31' THEN 'Y' ELSE 'N' END AS IS_ST_ADMIN /* 점포 관리자 */
			  , T0.PSWD AS PASSWORD
			  , T0.CP_CD
			  , T1.CP_SHORT_NM
			  , T1.CP_NM
			  , T0.BLONG_STORE_CD
			  , T2.STORE_NM
			  , T0.BLONG_TNANT_CD
			  , T3.TNANT_NM
			  , 'W' AS MAIN_LAYOUT_PAGE_CODE
			  , 'Y' AS IS_USE_SHORTCUT
			  , T86.PSWD_UPDT_DTMS
			  , CASE WHEN DATEDIFF( DAY, T86.PSWD_UPDT_DTMS, GETDATE() ) > 90 THEN 'Y' ELSE 'N' END CHG_PW /* Y : 변경 필요, N : 변경 완료*/
			  , dbo.fn_userlock('FIC07049') AS ACCOUNT_LOCK /* Y : LOCK, N : UNLOCK 또한 ";"로 split, 로그인 실패 횟수 및 계정잠금일자 추출 */
			  , T0.TEMP_PSWD_YN
			  , T0.TEMP_PSWD_CNGINFO
			  , T0.EMP_FLG_CD
			  , T0.LANG_FLG
			  , T0.GRP_ID_M
	 FROM  TBBA064 T0 WITH (NOLOCK)
	 			LEFT OUTER JOIN TBBA001 T1 WITH (NOLOCK) ON T0.CP_CD = T1.CP_CD
	 			LEFT OUTER JOIN TBBA002 T2 WITH (NOLOCK) ON T0.CP_CD = T2.CP_CD AND T0.BLONG_STORE_CD = T2.STORE_CD
	 			LEFT OUTER JOIN TBBA003 T3 WITH (NOLOCK) ON T0.CP_CD = T3.CP_CD AND T0.BLONG_STORE_CD = T3.STORE_CD AND T0.BLONG_TNANT_CD = T3.TNANT_CD
	 			LEFT OUTER JOIN TBCO006 T6 WITH (NOLOCK) ON T0.CP_CD = T6.CP_CD AND T0.GRP_ID = T6.AUTH_ID AND T6.USE_YN = 'Y'
	 			LEFT OUTER JOIN TBBA086 T86 WITH (NOLOCK) ON T0.USER_ID = T86.USER_ID
	 WHERE HFFC_FLG_CD = '1' /*재직 구분 코드[00024]1재직, 2퇴직*/
	   AND T0.USER_ID = 'FIC07049'
	   AND T0.USE_YN = 'Y';
	   
-- FIC08727	  
SELECT * FROM TBBA087 WHERE USER_ID = 'FIC07049' ORDER BY ACCOUNT_LOCK_DTMS DESC;

-- FIC08727
SELECT * FROM TBBA064 WHERE USER_ID = 'FIC07049' ORDER BY UPDT_DTMS  DESC;


select  *--MASTER.DBO.DEC_VARCHAR_INS( 0, 'PWD' ,  'A1ED5D4B76E92B7CB3D88D350C9A05DD09D87D51812DB434170833312E6536AC' )
from TBCO006
--where USER_ID = 'FIC07049';
--where auth_id = 'USER_LV1';


SELECT ISNULL(MAX(SEQ_NO)+1, 1) AS NEW_SEQ_NO
			FROM TBBA087
WHERE USER_ID = 'FIC07049';				
			
SELECT SEQ_NO
			 , USER_ID
			 , LOGIN_YN
			 , ACCOUNT_LOCK_YN
			 , ACCOUNT_LOCK_DTMS
			 , CP_CD
			 , UPDTER_ID
FROM TBBA087
WHERE USER_ID = 'FIC07049'


SELECT *
     , MASTER.DBO.ENC_VARCHAR_INS( 0, 'PWD', 'Cloud12#$' )
     , case when pswd = 'A1ED5D4B76E92B7CB3D88D350C9A05DD09D87D51812DB434170833312E6536AC' then 1 else 0 end
FROM TBBA086
WHERE USER_ID = 'FIC07049';	